### ISSUE TITLE
Private Group / Database

### ISSUE THREAD

**Issue by daenuprobst** [ojacquemart/ng2-euro-bets#18]
As far as I can see, all leagues are stored in your Firebase database. If I would want to run this web app for a small team, should I set up a free tier Firebase account on my own, fork this repo and change the Firebase constant?

**Comment by ojacquemart** [comment]
Yes, you juste have to change the constant in https://github.com/ojacquemart/ng2-euro-bets/blob/master/src/app/core/services/firebase/firebase.constants.ts#L1
It will provide an usable app to bet on the matches.
You will have to setup your auth configuration.

There is a second step that is still in progress: the tables update. It will be done by the https://github.com/ojacquemart/spring-euro-bets project. I will document how to do the setup.

I will share an app usable by everyone, this week (https://europronos.firebaseapp.com, I think) (Yes, I know the euro just starts next friday :))
It won't be private but you could have your team. Users will sign in with facebook, twitter, facebook...

**Comment by daenuprobst** [comment]
Would be awesome if I could set it up this week end...

**Comment by ojacquemart** [comment]
I am working on it ;)
I will keep you posted.

**Comment by ojacquemart** [comment]
https://europronos.firebaseapp.com is launched! You can join and share it :)

I still have a few things to do if you are still willing  to deploy your own version

**Comment by ojacquemart** [comment]
I close. I think you have found a better bets app ;)
