### ISSUE TITLE
je n'apparais plus dans mon équipe depuis samedi 18 juin ?

### ISSUE THREAD

**Issue by olivierroux** [ojacquemart/ng2-euro-bets#24]
Bonjour

Je vous écris pour vous signaler un problème.
En effet depuis samedi 18 juin après le match belgique irlande , j'ai disparu du classement de mon equipe " les pronosniqueurs " . j'ai donc essayer de sortir de mon equipe et d'y rerentrer . j'apparait bien dans le nombre de personnes mais n'apparait pas dans le classement alors que je suis tout de même en tête de mon groupe.
merci de faire le nécessaire dans les plus bref délai.

Autre problème: je tiens juste a signaler que pour le match d'ouverture FRANCE ROUMANIE j'avais mis 2 a 0 pour la FRANCE et que rien n'est apparu. après je comprends que pour ca vous ne pouviez rien faire car tout le monde pourrais dire ce qu'il veut mais c'est dommage .

Sinon super idéé de faire ca pour les entreprises

bonne journée

olivier roux

**Comment by ojacquemart** [comment]
Bonjour,

Après relancement de la routine du calcul du classement, vous êtes à nouveau dans votre équipe ;)

Par contre, pour le pari manquant, je ne peux rien faire :)

Bons pronos pour la suite de la compétition ;)

Merci pour votre retour! :+1:

**Comment by olivierroux** [comment]
merci

Le 20 juin 2016 à 10:52, Olivier Jacquemart notifications@github.com a
écrit :

> Bonjour,
> 
> Après relancement de la routine du calcul du classement, vous êtes à
> nouveau dans votre équipe ;)
> 
> Par contre, pour le pari manquant, je ne peux rien faire :)
> 
> Bons pronos pour la suite de la compétition ;)
> 
> Merci pour votre retour! 👍
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ojacquemart/ng2-euro-bets/issues/24#issuecomment-227085022,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATHEniF5tpMqcK4oOddtWJ6Ry-7xQE9Mks5qNlS6gaJpZM4I5bHa
> .

## 

Olivier ROUX
Adjoint LSE - JV - EPB
Membre du comité de marché MUSIQUE / VIDEO
AUCHAN Annecy
0450242309
8401
oroux@auchan.fr

**Comment by olivierroux** [comment]
bonjour

une petite question pour les pronostiques de la phase finale.
Le score a mettre est a la fin du temps réglementaire, ou des prolongationS
?

Le 20 juin 2016 à 11:15, OLIVIER ROUX oroux@auchan.fr a écrit :

> merci
> 
> Le 20 juin 2016 à 10:52, Olivier Jacquemart notifications@github.com a
> écrit :
> 
> > Bonjour,
> > 
> > Après relancement de la routine du calcul du classement, vous êtes à
> > nouveau dans votre équipe ;)
> > 
> > Par contre, pour le pari manquant, je ne peux rien faire :)
> > 
> > Bons pronos pour la suite de la compétition ;)
> > 
> > Merci pour votre retour! 👍
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/ojacquemart/ng2-euro-bets/issues/24#issuecomment-227085022,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ATHEniF5tpMqcK4oOddtWJ6Ry-7xQE9Mks5qNlS6gaJpZM4I5bHa
> > .
> 
> ## 
> 
> Olivier ROUX
> Adjoint LSE - JV - EPB
> Membre du comité de marché MUSIQUE / VIDEO
> AUCHAN Annecy
> 0450242309
> 8401
> oroux@auchan.fr

## 

Olivier ROUX
Adjoint LSE - JV - EPB
Membre du comité de marché MUSIQUE / VIDEO
AUCHAN Annecy
0450242309
8401
oroux@auchan.fr

**Comment by ojacquemart** [comment]
Bonjour,

Je dois publier une actualité à ce sujet.

En cas de prolongations, le score à renseigner est le score à la fin des prolongations.
Le résultat qui sera considéré est donc le résultat avant les tirs au but.

L'aide a été mise à jour: https://euro2016pronos.firebaseapp.com/#/help

**Comment by olivierroux** [comment]
ok merci

Le 23 juin 2016 à 15:51, Olivier Jacquemart notifications@github.com a
écrit :

> Bonjour,
> 
> Je dois publier une actualité à ce sujet.
> 
> En cas de prolongations, le score à renseigner est le score à la fin des
> prolongations.
> Le résultat qui sera considéré est donc le résultat avant les tirs au but.
> 
> L'aide a été mise à jour: https://euro2016pronos.firebaseapp.com/#/help
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ojacquemart/ng2-euro-bets/issues/24#issuecomment-228056369,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATHEnr-SX9lEHjI49-Q3kVS-ryDI4TjMks5qOo9lgaJpZM4I5bHa
> .

## 

Olivier ROUX
Adjoint LSE - JV - EPB
Membre du comité de marché MUSIQUE / VIDEO
AUCHAN Annecy
0450242309
8401
oroux@auchan.fr
