### ISSUE TITLE
bug|idée: 

### ISSUE THREAD

**Issue by sevmartin** [ojacquemart/ng2-euro-bets#26]
...Bonjour,

Je n'apparais plus dans mon équipe DP Vente d'Equipements, je ne suis plus dans le classement alors que j'ai 138 points.
sevmartin@auchan.fr

Merci de mettre à jour !

**Comment by ojacquemart** [comment]
Bonjour,

Vous aviez quittée l'équipe?

Je vous ai réaffectée à l'équipe et mis à jour le classement ;)
