### ISSUE TITLE
bug|idée: 

### ISSUE THREAD

**Issue by gf1984** [ojacquemart/ng2-euro-bets#27]

**Comment by ojacquemart** [comment]
C'est corrigé :)

Le classement final est à jour.

**Comment by gf1984** [comment]
Super j'ai vu ça ce matin
Merci Olivier

Le lundi 11 juillet 2016, Olivier Jacquemart notifications@github.com a
écrit :

> C'est corrigé :)
> 
> Le classement final est à jour.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ojacquemart/ng2-euro-bets/issues/27#issuecomment-231656956,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATcXeAngrwEouA3ftjb6gyg84-QkpcyLks5qUes8gaJpZM4JI8ID
> .

## 

Gaëtan Fréville
Responsable Adjoint
Auchan Drive Nice
